wandb_version: 1

model_id:
  desc: null
  value: google/gemma-1.1-2b-it
dataset_name:
  desc: null
  value: VideoFinder
precision:
  desc: null
  value: bf16
n_freeze:
  desc: null
  value: 12
lr:
  desc: null
  value: 0.0002
n_eval_samples:
  desc: null
  value: 10
max_seq_len:
  desc: null
  value: 1024
epochs:
  desc: null
  value: 3
gradient_accumulation_steps:
  desc: null
  value: 4
batch_size:
  desc: null
  value: 1
log_model:
  desc: null
  value: true
mom:
  desc: null
  value: 0.9
gradient_checkpointing:
  desc: null
  value: true
freeze_embed:
  desc: null
  value: true
total_train_steps:
  desc: null
  value: 75
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.39.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1715275206.0
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      - 86
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      - 86
      - 105
      3:
      - 2
      - 15
      - 16
      - 23
      4: 3.11.4
      5: 0.16.6
      6: 4.39.2
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
