wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.39.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1715286463.0
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 86
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      - 86
      - 105
      3:
      - 2
      - 15
      - 16
      - 23
      4: 3.11.4
      5: 0.16.6
      6: 4.39.2
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
